id: 2026-02-03_package.json
title: Work on package.json
created_at: "2026-02-03T15:49:21-08:00"
completed_at: "2026-02-03T16:09:40-08:00"
source: PRE_TOOL_USE
status: ACTIVE
session_id: 74a6ca7d-2ba8-46a2-9fb1-4b0b8d49156d
lineage:
  tools_used:
    - Edit
    - Write
  files_changed:
    - /Users/justintieu/Documents/github/provus-ai-assistant/data-adapters/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/data-schema-migration/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-email-agent/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-profet/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-ai-web/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/application-services/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/external-connectors/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-mcp-sfdc/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/.husky/pre-commit
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/workspaces.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/validation.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/client-sdk/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/.woodpecker/.provus-ai-web.yml
    - /Users/justintieu/Documents/github/provus-ai-assistant/.woodpecker/.provus-email-agent.yml
    - /Users/justintieu/Documents/github/provus-ai-assistant/.woodpecker/.data-adapters.yml
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-ai-web/scripts/production-build.js
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-ai-web/package-scripts.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/data-adapters/AGENTS.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/skills/validate/SKILL.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.husky/README.md
  agents_spawned: []
