id: 2026-01-30_SKILL.md
title: Work on SKILL.md
created_at: "2026-01-30T11:49:30-08:00"
completed_at: "2026-01-30T12:09:25-08:00"
source: PRE_TOOL_USE
status: ACTIVE
session_id: f0287f7e-7250-4cff-a0f2-b1b99ba7985e
lineage:
  tools_used:
    - Edit
    - Write
  files_changed:
    - /Users/justintieu/.claude/bin/claude-usage.mjs
    - /private/tmp/claude/-Users-justintieu-Documents-github-provus-ai-assistant/f0287f7e-7250-4cff-a0f2-b1b99ba7985e/scratchpad/compare.mjs
    - /private/tmp/claude/-Users-justintieu-Documents-github-provus-ai-assistant/f0287f7e-7250-4cff-a0f2-b1b99ba7985e/scratchpad/analyze.mjs
    - /private/tmp/claude/-Users-justintieu-Documents-github-provus-ai-assistant/f0287f7e-7250-4cff-a0f2-b1b99ba7985e/scratchpad/analyze2.mjs
    - /private/tmp/claude/-Users-justintieu-Documents-github-provus-ai-assistant/f0287f7e-7250-4cff-a0f2-b1b99ba7985e/scratchpad/find_diff.mjs
    - skills/pai-usage-audit/SKILL.md
    - /Users/justintieu/.claude/bin/audit-usage.mjs
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/README.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/agent-framework/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/agent-runtime/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/application-services/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/core-infrastructure/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/data-adapters/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/provus-mcp-sfdc/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/salesforce/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/data-schema-migration/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/external-connectors/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/provus-email-agent/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/provus-profet/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/provus-ai-web/index.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/shared-ci.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-runtime/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/application-services/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/core-infrastructure/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/external-connectors/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-mcp-sfdc/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/client-sdk/package.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/client-sdk/src/types.ts
  agents_spawned: []
