id: 2026-01-31_validate.md
title: Work on validate.md
created_at: "2026-01-31T20:53:14-08:00"
completed_at: null
source: PRE_TOOL_USE
status: INACTIVE
session_id: 27962f51-6b32-48d6-a9b8-c2b0e1f1330b
lineage:
  tools_used:
    - Write
  files_changed:
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/rules/validation.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/.claude/skills/validate/SKILL.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-ai-web/validate.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-runtime/validate.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/data-adapters/validate.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/validate.json
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-ai-web/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-runtime/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/data-adapters/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/agent-framework/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/core-infrastructure/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/data-schema-migration/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/external-connectors/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-email-agent/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-mcp-sfdc/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/provus-profet/validate.md
    - /Users/justintieu/Documents/github/provus-ai-assistant/application-services/validate.md
  agents_spawned: []
